### ISSUE TITLE
Feature request: allow overriding AppImage updInfo

### ISSUE THREAD

**Issue by mgord9518** [AppImageCommunity/AppImageUpdate#209]
For appimageupdatetool, a `-u, --update-info` flag would be useful, allowing users to switch AppImage channels if multiple are available (especially in scripts).

For example, someone updating an AppImage who would like to switch from stable to beta may do so with `./appimageupdatetool... -u "new|update|info|updateme-beta.AppImage" "updateme-stable.AppImage"`

**Comment by probonopd** [comment]
Each AppImage shold always update within the same channel.
E.g. an AppImage in the beta channel should always update to the next beta, and release versions should always update to release versions, and so on.

**Comment by mgord9518** [comment]
@probonopd this would also allow for AppImage implementations that don't use SquashFS (or store desktop integration in the exact same way) to be updated manually, giving some more flexibility. I'd be willing to learn some C++ and send a PR if the problem is just not wanting to implement an extra feature.

**Comment by TheAssassin** [comment]
I highly disagree with @probonopd, and therefore reopen the issue. The API supports this already because it's a useful feature for many, many applications. The two frontends (CLI and GUI) just need to add a parameter for this. PRs welcome.

**Comment by probonopd** [comment]
Why make things more complicated, do you have a use case @TheAssassin?

**Comment by mgord9518** [comment]
@probonopd how would it make things more complicated?

**Comment by TheAssassin** [comment]
@probonopd there are so many. For instance, one can easily test an update with new infrastructure or a different syntax. Also, you're able to allow users to update to a beta release manually. The already-existing API is designed exactly for allowing more than one update channel (e.g., daily, beta, stable).

Also, since the API already provides that feature, the change proposed in #214 is very small. It's just 4 lines.
