### ISSUE TITLE
Update panel shortcut

### ISSUE THREAD

**Issue by michaelhays** [AppImageCommunity/AppImageUpdate#226]
On Linux Mint, you can click "Add to panel" to show an AppImage program in your desktop panel, next to the start menu.

However, whenever you update an AppImage using AppImageUpdate, this breaks that panel icon, since it now refers to the old image, which is deleted in the update process.

Is there a way to automatically update the panel shortcut so that points to the new AppImage?

**Comment by probonopd** [comment]
No, since "Add to panel" uses the old AppImage.
But you don't have to delete the old AppImage. The old and new one can co-exist. This way you can have multiple versions of the same application - it's a feature, not a bug.

Personally I don't like it when in order to get a newer version, the old (known good) version is taken away from me.
